baseURL = "https://danfromit.com/"
languageCode = "en-gb"
title = "dan from IT"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20
googleAnalytics = "UA-131009415-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  description = "Dan is from IT. He works on projects. He also rants about IT and projects."
  facebook = ""
  twitter = "https://twitter.com/danieljav"
  instagram = ""
  youtube = ""
  github = "https://github.com/djavorszky"
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/header.jpg"
  recent_posts_number = 5
  show_reading_time = true
